name: croissant_mirroring

on: [push, delete]

jobs:
  mirroring:
    runs-on: ubuntu-latest
    steps:
      - name: Mirroring
        uses: pixta-dev/repository-mirroring-action@main
        with:
          target_repo_url: 'https://github.com/EpitechPromo2028/B-DOP-200-MPL-2-1-bschocolatine-killian.cassard.git'
          ssh_private_key: ${{ secrets.SSH_PASS }}

