name: croissant_size

on:
  push:
    branches:
      - main

jobs:
  get_size:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Display current branch
        run: echo "Current branch is ${{ github.ref }}"

      - name: Get repository size
        run: du -skh --exclude=.git

