name: Repo size

on:
  push:
    branches:
      - main

jobs:
  get_repository_size:
    runs-on: ubuntu-latest

    steps:
    - name: Fetch repo
      uses: actions/checkout@v2

    - name: Display branch name
      run: echo "Running on  branch: ${{ github.ref }}"

    - name: Calculate repository size
      run: du -skh --exclude=".git" .
