name: croissant_mirroring

on: [push, delete]

jobs:
  mirroring:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Mirroring
        uses: pixta-dev/repository-mirroring-action@v1.1.1
        with:
          target_repo_url: git@github.com:EpitechPromo2028/B-DOP-200-MPL-2-1-bschocolatine-killian.cassard.git
          ssh_private_key: ${{ secrets.SSH_PASS }}
